# Load Packages

```{r setup, include=FALSE}

# Load Packages
library(fhswf)
library(ggplot2)
library(tsibbledata) #0.4.1
library(dplyr)
library(tsibble)
library(fable)
library(fabletools)
library(feasts)
library(distributional)
library(lubridate)
library(broom)
library(readr)
library(tidyr)
library(datasets)
library(forecast)
library(timeDate)
library(qlcal)
library(devtools)
library(zoo)
library(corrplot)
library(scales)
library(fable.prophet)
library(mgcv)
library(MEFM)
library(TTR)
load_all()
# devtools::document()
```

# Define data-paths and load german holidays

```{r, echo=TRUE, message=FALSE}

# Define datapaths
power_consum_path <- "dataset\\stunde_2015_2024\\Realisierter_Stromverbrauch_201501010000_202407090000_Stunde.csv"
power_generation_path <- "dataset\\stunde_2015_2024\\Realisierte_Erzeugung_201501010000_202407090000_Stunde.csv"
power_consum_smard_prediction_path <- "dataset\\propgnose_vom_smard\\Prognostizierter_Stromverbrauch_202401010000_202407090000_Stunde.csv"

```

# Load german holidays for 2015-2024

```{r, echo=TRUE, message=FALSE}
german_holidays <- load_german_holidays(from_year = 2015, to_year = 2024, location="/DE")
german_holidays <- german_holidays |> 
  mutate(date = as.Date(date)) |>
  select(localName, date)
```

# Load and cleanup power-consum, filling gaps and droping duplicates, keeping first value. Creating features. 

```{r, echo=TRUE, message=FALSE}
# Load Smard Predictions
power_consum_smard_prediction_loaded <- load_power_consum(path=power_consum_smard_prediction_path)
raw_smard_pred <- power_consum_smard_prediction_loaded$raw_data
cleaned_smard_pred <- power_consum_smard_prediction_loaded$cleaned_data

cleaned_smard_pred <- cleaned_smard_pred |>
  mutate(.model = "SMARD")
names(cleaned_smard_pred)[names(cleaned_smard_pred) == "PowerConsum"] <- ".mean"

# Load PowerConsum Data
power_consum_loaded <- load_power_consum(path=power_consum_path)
raw_power_consum <- power_consum_loaded$raw_data
cleaned_power_consum <- power_consum_loaded$cleaned_data

rm(power_consum_loaded)
rm(power_consum_smard_prediction_loaded)
rm(power_consum_path)
rm(power_consum_smard_prediction_path)
rm(power_generation_path)

```

# Generate more features

```{r, echo=TRUE, message=FALSE}

cleaned_power_consum$localName[is.na(cleaned_power_consum$localName)] = "Working-Day"

cleaned_power_consum$MeanLastWeek <- rollapply(cleaned_power_consum$PowerConsum, width = 24*8, FUN = function(x) mean(x[1:(24*8-25)]), align = "right", fill = NA) 

cleaned_power_consum$MeanLastTwoDays <- rollapply(cleaned_power_consum$PowerConsum, width = 24*3, FUN = function(x) mean(x[1:(24*3-25)]), align = "right", fill = NA) 

cleaned_power_consum$MaxLastOneDay <- rollapply(cleaned_power_consum$PowerConsum, width = 24*2, FUN = function(x) max(x[1:(24*2-25)]), align = "right", fill = NA) 

cleaned_power_consum$MinLastOneDay <- rollapply(cleaned_power_consum$PowerConsum, width = 24*2, FUN = function(x) min(x[1:(24*2-25)]), align = "right", fill = NA) 

# Check Correlation
cor <- cor(cleaned_power_consum[sapply(cleaned_power_consum, is.numeric)], method = c("pearson", "kendall", "spearman"), use = "complete.obs")

```


# Create different Plot for analysis

```{r echo=TRUE, message=FALSE}
load_all()
local_name_colors <- c(
  "Christi Himmelfahrt" = palette()[2],
  "Erster Weihnachtstag" = palette()[2],
  "Karfreitag" = palette()[2],
  "Neujahr" = palette()[2],
  "Ostermontag" = palette()[2],
  "Pfingstmontag" = palette()[2],
  "Reformationstag" = palette()[2],
  "Tag der Arbeit" = palette()[2],
  "Tag der Deutschen Einheit" = palette()[2],
  "Zweiter Weihnachtstag" = palette()[2],
  "Regulärer Tag" = palette()[1]
)


week_colors <- c(
  "Mo" = palette()[1],
  "Di" = palette()[1],
  "Mi" = palette()[1],
  "Do" = palette()[1],
  "Fr" = palette()[1],
  "Sa" = palette()[2],
  "So" = palette()[2]
)

working_colors <- c("1" = "#2E9FDF", "0" = "#FC4E07")

whw_colors <- c(
  "Feiertag\nKein Wochenende" = "black",
  "Kein Feiertag\nKein Wochenende" = "red",
  "Kein Feiertag\nWochenende" = "orange",
  "Feiertag\nWochenende" = "blue"
)

p <- cleaned_power_consum |>
    gg_tsdisplay(PowerConsum, plot_type = "partial", lag = 100)

ggsave(
  "plots/power_consum_acf_pacf.png",
  plot = p,
  width = 5.5,
  height = 3.7,
  dpi = 600
)

plot_calculated_features(
  cleaned_power_consum = cleaned_power_consum,
  file_name = "plots/MinLastOneDay.png", 
  x = "MinLastOneDay", 
  y = "PowerConsum", 
  x_label = "Minimaler Stromverbrauch vom letzten Tag [MW]",
  y_label = "Stromverbrauch [MW]"
)

plot_calculated_features(
  cleaned_power_consum = cleaned_power_consum,
  file_name = "plots/MaxLastOneDay.png", 
  x = "MaxLastOneDay", 
  y = "PowerConsum", 
  x_label = "Maximaler Stromverbrauch vom letzten Tag [MW]",
  y_label = "Stromverbrauch [MW]"
)

plot_calculated_features(
  cleaned_power_consum = cleaned_power_consum,
  file_name = "plots/MeanLastWeek.png", 
  x = "MeanLastWeek", 
  y = "PowerConsum", 
  x_label = "Durchschnittlicher Stromverbrauch der letzten 7 Tage [MW]",
  y_label = "Stromverbrauch [MW]"
)


plot_calculated_features(
  cleaned_power_consum = cleaned_power_consum,
  file_name = "plots/MeanLastTwoDays.png", 
  x = "MeanLastTwoDays", 
  y = "PowerConsum", 
  x_label = "Durchschnittlicher Stromverbrauch der letzten 2 Tage [MW]",
  y_label = "Stromverbrauch [MW]"
)

plot_histogram_by_group(
  cleaned_power_consum,
  group_name = "WorkdayHolidayWeekend",
  file_name = "plots\\workday_holiday_weekend_histogram.png",
  colors = whw_colors,
  x="PowerConsum",
  x_label = "Stromverbrauch [MW]",
  y_label = "Häufigkeit",
  name_0 = "Wochenende oder Feiertage",
  name_1 = "Werktag"
)


plot_histogram_by_group(
  cleaned_power_consum,
  group_name = "WorkDay",
  file_name = "plots\\workday_histogram.png",
  colors = working_colors,
  x="PowerConsum",
  x_label = "Stromverbrauch [MW]",
  y_label = "Häufigkeit",
  name_0 = "Wochenende oder Feiertage",
  name_1 = "Werktag"
)

plot_histogram_by_group(
  cleaned_power_consum,
  group_name = "Holiday",
  file_name = "plots\\holiday_histogram.png",
  colors = working_colors,
  x="PowerConsum",
  x_label = "Stromverbrauch [MW]",
  y_label = "Häufigkeit",
  name_0 = "Werktag oder Wochenende",
  name_1 = "Feiertag"
)

plot_histogram_by_group(
  cleaned_power_consum,
  group_name = "HolidayAndWorkDay",
  file_name = "plots\\holiday_workday_histogram.png",
  colors = working_colors,
  x="PowerConsum",
  x_label = "Stromverbrauch [MW]",
  y_label = "Häufigkeit",
  name_0 = "Wochenende oder Werktag",
  name_1 = "Feiertag am Werktag"
)

plot_by_group(
  cleaned_power_consum,
  group_name = "HolidayName",
  file_name = "plots\\holiday_boxplot.png",
  colors = local_name_colors,
  title = "Übersicht der einzelnen Feiertage",
  y="PowerConsum",
  y_label="Stromverbrauch [MW]",
  x_label="Jahre"
)

plot_by_group(
  cleaned_power_consum,
  group_name = "Weekday",
  file_name = "plots\\weekday_boxplot.png",
  colors = week_colors,
  title = "Übersicht der einzelnen Wochentage",
  y = "PowerConsum",
  y_label="Stromverbrauch [MW]",
  x_label="Jahre"
)

plot_by_group(
  cleaned_power_consum,
  group_name = "WorkDay",
  file_name = "plots\\workday_boxplot.png",
  colors = working_colors,
  title = "Übersicht, ob Feiertag (FALSE) oder Werktag (TRUE)",
  y = "PowerConsum",
  y_label="Stromverbrauch [MW]",
  x_label="Jahre"
)


plot_by_column(
  df = cleaned_power_consum,
  x = "Hour",
  y = "PowerConsum",
  x_label = "Stunden",
  y_label = "Stromverbrauch [MW]",
  file_name = "plots\\hour_boxplot.png",
  title = "Übersicht der einzelnen Stunden"
)

plot_by_column(
  df = cleaned_power_consum,
  x = "Month",
  y = "PowerConsum",
  x_label = "Monate",
  y_label = "Stromverbrauch [MW]",
  file_name = "plots\\month_boxplot.png",
  title = "Übersicht der einzelnen Monate"
)

plot_by_column(
  df = cleaned_power_consum,
  x = "Week",
  y = "PowerConsum",
  x_label = "Woche",
  y_label = "Stromverbrauch [MW]",
  file_name = "plots\\week_boxplot.png",
  title = "Übersicht der einzelnen Wochen"
)

plot_by_column(
  df = cleaned_power_consum,
  x = "Year",
  y = "PowerConsum",
  x_label = "Jahr",
  y_label = "Stromverbrauch [MW]",
  file_name = "plots\\year_boxplot.png",
  title = "Übersicht der einzelnen Jahre"
)

plot_year_month_week_day(
  df=cleaned_power_consum,
  date_column="DateIndex",
  y="PowerConsum",
  from_year=2015,
  to_year=2024,
  from_week=0,
  to_week=53,
  year_for_week=2018,
  from_day=1,
  to_day=30,
  month_for_day=4,
  year_for_day=2018,
  from_month=1,
  to_month=12,
  year_for_month=2018,
  holiday="Holiday",
  day_of_week = "Weekday"
)


```
# STL decomposition

```{r, echo=TRUE, message=FALSE}

p <-  cleaned_power_consum |>
  filter(year(DateIndex) == 2023, week(DateIndex) < 10) |>
  model(STL(
    PowerConsum ~ season(period = 24 * 365.25)
    + season(period = 24 * 7)
    + season(period = 24),
    robust = TRUE 
  )) |>
  components() |>
  autoplot() + labs(x = "Observation")

ggsave("plots/stl_decomposition.png",   
       plot = p,
       width = 5.5,
       height = 8,
       dpi = 600)

p

rm(p)
```

# Different Models

```{r, echo=TRUE, message=FALSE}
load_all()

train_power_consum <- cleaned_power_consum |>
  filter(year(DateIndex) > 2020 & (year(DateIndex) < 2024))

generate_models(model_name = "model/mean_naive_drift",
                train_power_consum = train_power_consum)

# generate_models(model_name = "model/arima_0_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_1_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_2_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_3_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_4_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_5_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/tslm_0_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "other_model/prophet_0_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_8_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_9_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_10_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_11_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_12_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_13_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_14_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_15_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_16_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_17_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "model/arima_18_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "other_model/prophet_1_2021_2023.rds",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_0",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_1",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_2",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_3",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_4",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_5",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_6",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_7",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_8",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "ensemble_model/version_9",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "other_model/version_10",
#                 train_power_consum = train_power_consum)
# 
# generate_models(model_name = "other_model/version_11",
#                 train_power_consum = train_power_consum)



```

# Load All Models and Metrics Evaluation


```{r, echo=TRUE, message=FALSE}
load_all()

ensembled_fc <- load_ensembled_models(
  days_to_forecast = 40,
  months_to_forecast = 6,
  year_to_forecast = 2024,
  starting_month = 1,
  real_data = cleaned_power_consum,
  smard_fc = cleaned_smard_pred,
  model_path = "ensemble_model"
)
all_forecasts_ensembled <- ensembled_fc$all_forecasts
raw_fc_ensembled <- ensembled_fc$raw_forecasts

fc <- load_all_model_results(
  days_to_forecast = 40,
  months_to_forecast = 6,
  year_to_forecast = 2024,
  starting_month = 1,
  smard_fc = cleaned_smard_pred,
  real_data = cleaned_power_consum
)

all_forecasts <- fc$combined_forecasts
raw_fc <- fc$raw_forecasts


metric_results <- calculate_metrics(fc_data = all_forecasts, fc_data_ensembled=all_forecasts_ensembled)
rm(fc)
rm(ensembled_fc)
```
# Create plots of best models

```{r, echo=TRUE, message=FALSE}
load_all()

# Plot best Model for single Models
name_of_best_model_for_single_model <- plot_forecast(
  all_forecasts = all_forecasts,
  metric_results = metric_results,
  cleaned_power_consum = cleaned_power_consum,
  raw_fc = raw_fc,
  month_to_plot = 1,
  days_to_plot = 40
)

# Plot best Model for ensembled Models
name_of_best_model_ensembled <- plot_forecast_ensembled(
  all_forecasts = all_forecasts_ensembled,
  metric_results = metric_results,
  cleaned_power_consum = cleaned_power_consum,
  month_to_plot = 1,
  days_to_plot = 40
)

# Residuals Compared with SMARD
plot_compare_with_smard(
  all_forecasts = all_forecasts_ensembled, 
  name_of_best_model = name_of_best_model_ensembled
  )


# LHM DHM representation
plot_representation_of_lhm_dhm_components(path_dhm = "ensemble_model/version_5/arima_2021_2023.rds",
                                          path_lhm = "ensemble_model/version_5/holiday_effect_2021_2023.rds",
                                          from_month = 1,
                                          to_month = 1,
                                          raw_fc_ensembled = raw_fc_ensembled)


```




